This is makeindex, version 2.15 [TeX Live 2020] (kpathsea + Thai support).
Scanning style file ./Main.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file Main.acn....done (16 entries accepted, 0 rejected).
Sorting entries....done (65 comparisons).
Generating output file Main.acr....done (20 lines written, 0 warnings).
Output written in Main.acr.
Transcript written in Main.alg.
